Django_8/Django_8/urls.py
from django.contrib import admin
from django.urls import path
from FBV import views  
from Eight.views import PlantCRUD_CBVView

urlpatterns = [
    path('admin/', admin.site.urls),  
    path('plant', views.plantV),  
    path('show',views.show),  
    path('edit/<int:id>/', views.edit, name='edit'),  
    path('update/<int:id>/', views.update, name='update'),  
    path('delete/<int:id>/', views.destroy),
    path('plants/', PlantCRUD_CBVView.as_view(), name='plant-crud'),  # For listing and creating
    path('plants/<int:id>/', PlantCRUD_CBVView.as_view(), name='plant-crud'), 
]

Django_8/Eight/models.py
from django.db import models

# Create your models here.
class PlantsDetail(models.Model):  
    pid = models.IntegerField(primary_key=True)  
    plant_name = models.CharField(max_length=100)  
 

Django_8/FBV/models.py
from django.db import models

class Plants(models.Model):  
    pid = models.CharField(max_length=20)  
    plant_name = models.CharField(max_length=100)  
    plant_price = models.IntegerField()
    class Meta:  
        db_table = "plantdata"  

Django_8/Eight/forms.py
from django import forms  
from .models import Plants
class PlantsForm(forms.ModelForm):  
    class Meta:  
        model = Plants  
        fields = "__all__"  

Django_8/FBV/forms.py
from django import forms  
from .models import Plants
class PlantsForm(forms.ModelForm):  
    class Meta:  
        model = Plants  
        fields = "__all__"  

Django_8/Eight/views.py
# views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import View
from .models import PlantsDetail

class PlantCRUD_CBVView(View):
    template_name = 'plant_crud.html'
    # Handle GET requests for reading data
    def get(self, request, *args, **kwargs):
        template_path = str(settings.BASE_DIR / 'templates' / 'plant_crud.html')
        if 'id' in kwargs:  # For single plant retrieval
            plant = get_object_or_404(PlantsDetail, pid=kwargs['id'])
            return render(request, template_path)
        else:  # For listing all plants
            plants = PlantsDetail.objects.all()
            return render(request, template_path)


    # Handle POST requests for creating or updating data
    def post(self, request, *args, **kwargs):
        if 'id' in kwargs:  # Updating an existing plant
            plant = get_object_or_404(PlantsDetail, pid=kwargs['id'])
            plant.pid = request.POST.get('id')
            plant.plant_name = request.POST.get('pname')
            plant.save()
            return redirect('plant-crud')
        else:  # Creating a new plant
            plant = PlantsDetail(pid=request.POST.get('id'),plant_name=request.POST.get('pname'))
            plant.save()
            return redirect('plant-crud')

    # Handle DELETE requests
    def delete(self, request, *args, **kwargs):
        print("State-previous")
        plant = get_object_or_404(PlantsDetail, pid=kwargs['id'])
        print("State-1")
        print(plant)
        plant.delete()
        return redirect('plant-crud')

Django_8/FBV/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404

from .forms import PlantsForm  
from .models import Plants  

def plantV(request):  
    if request.method == "POST":  
        form = PlantsForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = PlantsForm()  
    return render(request,'index.html',{'form':form})  

def show(request):  
    plants = Plants.objects.all()  
    return render(request,"show.html",{'plants':plants})  

def edit(request, id):  
    plant = get_object_or_404(Plants, id=id)  
    return render(request,'edit.html', {'plant':plant})  

def update(request, id):  
    plant = get_object_or_404(id=id)  
    form = PlantsForm(request.POST, instance = plant)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'plant': plant})  

def destroy(request, id):  
    plant = Plants.objects.get(id=id)  
    plant.delete()  
    return redirect("/show")  

Django_8/Eight/templates/plant_crude.html
<!-- plant_crud.html -->
<h1>Plant List</h1>

{% if plants %}
    <ul>
    {% for plant in plants %}
        <li>
            <form method="post" action="{% url 'plant-crud' plant.pid %}" style="display:inline;">
                {% csrf_token %}
                <input type="text" name="id" value="{{ plant.pid }}" />
                <input type="text" name="pname" value="{{ plant.plant_name }}" />
                <button type="submit">Update</button>
            </form>
            <form method="post" action="{% url 'plant-crud' plant.pid %}" style="display:inline;">
                {% csrf_token %}
                <input type="hidden" name="_method" value="delete">
                <button type="submit">Delete</button>
            </form>
        </li>
    {% endfor %}
    </ul>
{% endif %}

<h2>Add a New Plant</h2>
<form method="post" action="{% url 'plant-crud' %}">
    {% csrf_token %}
    <input type="text" name="id"/>
    <input type="text" name="pname"/>
    <button type="submit">Add Plant</button>
</form>

Django_8/FBV/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
</head>  
<body>  
<form method="POST" action="{% url 'update' plant.id %}/" class="post-form" action="/update/{{plant.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Plant Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="pid" id="id_pid" required maxlength="20" value="{{ plant.pid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Plant Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="plant_name" id="id_plant_name" required maxlength="100" value="{{ plant.plant_name }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Plant Price:</label>  
    <div class="col-sm-4">  
        <input type="text" name="plant_price" id="id_plant_price" required maxlength="254" value="{{ plant.plant_price }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

Django_8/FBV/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
</head>  
<body>  
<form method="POST" class="post-form" action="/plant">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Plant Id:</label>  
    <div class="col-sm-4">  
      {{ form.pid }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Plant Name:</label>  
    <div class="col-sm-4">  
      {{ form.plant_name }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Plant Price:</label>  
    <div class="col-sm-4">  
      {{ form.plant_price }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

Django_8/FBV/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Plant Records</title>  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Plant ID</th>  
        <th>Plant Name</th>  
        <th>Plant Price</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for plant in plants %}  
    <tr>  
        <td>{{ plant.pid }}</td>  
        <td>{{ plant.plant_name }}</td>  
        <td>{{ plant.plant_price }}</td>  
        <td>  
            <a href="/edit/{{ plant.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ plant.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/plant" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  